{
  "success": 1,
  "data": {
    "rowcount": 1,
    "totalrows": "1",
    "estimatedrows": false,
    "pagesize": 0,
    "pagecount": null,
    "page": 1,
    "offset": 0,
    "startrow": 0,
    "resultset": [
      {
        "id": "342",
        "status": "P",
        "time_modified": "2018-01-27 02:53:37",
        "type": "BINARY",
        "name": "Baker",
        "code": "BAKER",
        "position_x": "89.54095500",
        "position_y": "-5.42230320",
        "position_z": "-39.71175400",
        "info_url": null,
        "habitable_zone_inner": "0.75000000",
        "habitable_zone_outer": "1.36000000",
        "frost_line": "2.45000000",
        "description": "Though the binary star system is of great interest to the scientific community, Baker has seen little use by the general civilian population. Poor placement of the planets makes terraforming impossible, and, as a result, the system\u2019s sparse population is mostly confined to Xenia, a Covalex shipping hub near Baker-III. This relative isolation has made it an ideal spot for underground racing, the most well-known of which is the Able Baker Challenge.   ",
        "shader_data": null,
        "affiliation": [
          {
            "id": "1",
            "name": "UEE",
            "code": "uee",
            "color": "#48bbd4",
            "membership.id": "756"
          }
        ],
        "celestial_objects": [
          {
            "id": "1943",
            "time_modified": "2015-10-10 02:44:20",
            "type": "JUMPPOINT",
            "designation": "Baker - Tayac",
            "name": null,
            "code": "BAKER.JUMPPOINTS.TAYAC",
            "age": "0.00000000",
            "distance": "2.15400000",
            "latitude": "-12.56480000",
            "longitude": "-108.69600000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1944",
            "time_modified": "2015-10-10 02:44:31",
            "type": "JUMPPOINT",
            "designation": "Baker - Kiel",
            "name": null,
            "code": "BAKER.JUMPPOINTS.KIEL",
            "age": "0.00000000",
            "distance": "7.15580000",
            "latitude": "-22.00000000",
            "longitude": "-12.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1945",
            "time_modified": "2015-10-10 02:43:52",
            "type": "JUMPPOINT",
            "designation": "Baker - Hadur",
            "name": null,
            "code": "BAKER.JUMPPOINTS.HADUR",
            "age": "0.00000000",
            "distance": "6.00000000",
            "latitude": "18.97240000",
            "longitude": "96.91050000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1946",
            "time_modified": "2015-09-15 14:34:05",
            "type": "JUMPPOINT",
            "designation": "Baker - Osiris",
            "name": null,
            "code": "BAKER.JUMPPOINTS.OSIRIS",
            "age": "0.00000000",
            "distance": "1.00000000",
            "latitude": "14.00000000",
            "longitude": "172.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": "0",
            "fairchanceact": "0",
            "show_orbitlines": "0",
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1947",
            "time_modified": "2015-10-10 02:43:38",
            "type": "JUMPPOINT",
            "designation": "Baker - Pallas",
            "name": null,
            "code": "BAKER.JUMPPOINTS.PALLAS",
            "age": "0.00000000",
            "distance": "4.00000000",
            "latitude": "28.00000000",
            "longitude": "-147.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1948",
            "time_modified": "2018-01-13 02:35:30",
            "type": "STAR",
            "designation": "Baker A",
            "name": null,
            "code": "BAKER.STARS.BAKERA",
            "age": "0.00000000",
            "distance": "0.07830000",
            "latitude": "0.00000000",
            "longitude": "225.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "-1.00000000",
            "description": null,
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": {
              "orbitalMin": 1,
              "orbitalMax": 5,
              "orbitalFactor": 1,
              "sun": {
                "color1": "#ed830b",
                "color2": "#d9d919",
                "flare1": 0.265,
                "flare2": 0.5,
                "flare3": 0.265,
                "flare4": 0.5,
                "flare5": 0.5,
                "flare6": 0.1,
                "sphere": 1,
                "texture": 1,
                "corona": 1,
                "glow": 0.5,
                "alpha": 1,
                "rotation1": 0.6,
                "rotation2": 0.6,
                "map": 0,
                "iterations": 0,
                "scaleMin": 1,
                "scaleMax": 1,
                "scalePeriod": 1
              },
              "radius": 0.05
            },
            "size": "571567.25769000",
            "subtype_id": "60",
            "parent_id": null,
            "subtype": {
              "id": "60",
              "name": "Main Sequence-Dwarf-K",
              "type": "STAR"
            },
            "affiliation": [],
            "population": []
          }, {
            "id": "2424",
            "time_modified": "2018-01-25 01:34:29",
            "type": "PLANET",
            "designation": "Baker I",
            "name": null,
            "code": "BAKER.PLANET.BAKERI",
            "age": null,
            "distance": "0.50000000",
            "latitude": null,
            "longitude": "-25.49879000",
            "axial_tilt": null,
            "orbit_period": null,
            "description": "With a decaying orbit bringing the small planet closer to the system\u2019s stars, Baker I is expected to collide with Baker A in approximately one hundred and fifty million years.",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "1",
            "sensor_economy": "4",
            "sensor_danger": "5",
            "shader_data": null,
            "size": "3043.00000000",
            "subtype_id": "27",
            "parent_id": null,
            "subtype": {
              "id": "27",
              "name": "Iron Planet",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2764"
              }
            ],
            "population": [],
            "texture": {
              "slug": "woi3qpzk18w05",
              "source": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/source\/Planet_Iron.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/post\/Planet_Iron.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/product_thumb_large\/Planet_Iron.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/subscribers_vault_thumbnail\/Planet_Iron.jpg"
              }
            }
          }, {
            "id": "2425",
            "time_modified": "2018-01-25 01:35:01",
            "type": "PLANET",
            "designation": "Baker II",
            "name": null,
            "code": "BAKER.PLANET.BAKERII",
            "age": null,
            "distance": "1.00000000",
            "latitude": null,
            "longitude": "132.16400000",
            "axial_tilt": null,
            "orbit_period": null,
            "description": "The atmosphere of this smog planet is so extremely toxic and corrosive that it is able to rapidly dissolve most modern hull and construction materials; making approaching the world a difficult and risky proposition. ",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "1",
            "sensor_economy": "4",
            "sensor_danger": "5",
            "shader_data": null,
            "size": "6302.00000000",
            "subtype_id": "20",
            "parent_id": null,
            "subtype": {
              "id": "20",
              "name": "Smog Planet",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2765"
              }
            ],
            "population": [],
            "texture": {
              "slug": "8nd3j4zcsqfmz",
              "source": "https:\/\/robertsspaceindustries.com\/media\/8nd3j4zcsqfmzr\/source\/Planet_Smog.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/8nd3j4zcsqfmzr\/post\/Planet_Smog.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/8nd3j4zcsqfmzr\/product_thumb_large\/Planet_Smog.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/8nd3j4zcsqfmzr\/subscribers_vault_thumbnail\/Planet_Smog.jpg"
              }
            }
          }, {
            "id": "2426",
            "time_modified": "2018-01-25 01:35:12",
            "type": "PLANET",
            "designation": "Baker III",
            "name": null,
            "code": "BAKER.PLANET.BAKERIII",
            "age": null,
            "distance": "5.00000000",
            "latitude": null,
            "longitude": "165.15760000",
            "axial_tilt": null,
            "orbit_period": null,
            "description": "Due to its expanding planetary radius, the Department of Transportation and Navigation have designated the ice giant as hazardous and recommend that civilians do not land on Baker III.   ",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BLUE",
            "sensor_population": "1",
            "sensor_economy": "4",
            "sensor_danger": "5",
            "shader_data": null,
            "size": "24053.00000000",
            "subtype_id": "25",
            "parent_id": null,
            "subtype": {
              "id": "25",
              "name": "Ice Giant",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2766"
              }
            ],
            "population": [],
            "texture": {
              "slug": "94je2ho8w8fbe",
              "source": "https:\/\/robertsspaceindustries.com\/media\/94je2ho8w8fber\/source\/Planet_Neptune.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/94je2ho8w8fber\/post\/Planet_Neptune.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/94je2ho8w8fber\/product_thumb_large\/Planet_Neptune.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/94je2ho8w8fber\/subscribers_vault_thumbnail\/Planet_Neptune.jpg"
              }
            }
          }, {
            "id": "2427",
            "time_modified": "2018-01-25 01:35:24",
            "type": "PLANET",
            "designation": "Baker IV",
            "name": null,
            "code": "BAKER.PLANET.BAKERIV",
            "age": null,
            "distance": "7.90000000",
            "latitude": null,
            "longitude": "156.14570000",
            "axial_tilt": null,
            "orbit_period": null,
            "description": "There are very few landmarks on Baker IV\u2019s atmosphere-free surface beyond the Shubin Interstellar outpost, GIO, from which the corporation oversees its mining operations across the planet.\n",
            "info_url": null,
            "habitable": "1",
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "2",
            "sensor_economy": "7",
            "sensor_danger": "3",
            "shader_data": null,
            "size": "4781.00000000",
            "subtype_id": "55",
            "parent_id": null,
            "subtype": {
              "id": "55",
              "name": "Terrestrial Rocky",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2767"
              }
            ],
            "population": [],
            "texture": {
              "slug": "jnd5qqer9z13g",
              "source": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/source\/Planet_Rocky.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/post\/Planet_Rocky.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/product_thumb_large\/Planet_Rocky.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/subscribers_vault_thumbnail\/Planet_Rocky.jpg"
              }
            }
          }, {
            "id": "2528",
            "time_modified": "2018-01-13 02:35:17",
            "type": "STAR",
            "designation": "Baker B",
            "name": null,
            "code": "BAKER.STAR.BAKERB",
            "age": null,
            "distance": "0.07830000",
            "latitude": null,
            "longitude": "45.00000000",
            "axial_tilt": null,
            "orbit_period": null,
            "description": null,
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": {
              "orbitalMin": 1,
              "orbitalMax": 5,
              "orbitalFactor": 1,
              "sun": {
                "color1": "#ed830b",
                "color2": "#d9d919",
                "flare1": 0.265,
                "flare2": 0.5,
                "flare3": 0.265,
                "flare4": 0.5,
                "flare5": 0.5,
                "flare6": 0.1,
                "sphere": 1,
                "texture": 1,
                "corona": 1,
                "glow": 0.5,
                "alpha": 1,
                "rotation1": 0.6,
                "rotation2": 0.6,
                "map": 0,
                "iterations": 0,
                "scaleMin": 1,
                "scaleMax": 1,
                "scalePeriod": 1
              },
              "radius": 0.05
            },
            "size": "621354.25400000",
            "subtype_id": "60",
            "parent_id": null,
            "subtype": {
              "id": "60",
              "name": "Main Sequence-Dwarf-K",
              "type": "STAR"
            },
            "affiliation": [],
            "population": []
          }, {
            "id": "2598",
            "time_modified": "2015-10-09 20:13:07",
            "type": "MANMADE",
            "designation": "Covalex Shipping Hub Xenia",
            "name": null,
            "code": "BAKER.STATION.COVALEXSHIPPINGHUBXENIA",
            "age": null,
            "distance": "5.98656900",
            "latitude": null,
            "longitude": "156.15648400",
            "axial_tilt": null,
            "orbit_period": null,
            "description": "Operated by Covalex Shipping, the Xenia station not only serves as a major cargo transfer hub for goods heading throughout the Empire, but also houses most of the permanent population in Baker system.\n",
            "info_url": null,
            "habitable": "1",
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "3",
            "sensor_economy": "6",
            "sensor_danger": "3",
            "shader_data": {
              "orbitalMin": 1,
              "orbitalMax": 5,
              "orbitalFactor": 1,
              "orbitalColor": "rgb(26,86,124)",
              "orbitalHighlightColor": "rgb(128,128,255)",
              "radius": 0.03
            },
            "size": null,
            "subtype_id": "44",
            "parent_id": null,
            "subtype": {
              "id": "44",
              "name": "Space Station",
              "type": "MANMADE"
            },
            "affiliation": [],
            "population": []
          }
        ],
        "aggregated_size": "7.90000000",
        "aggregated_population": 7.4,
        "aggregated_economy": 2.91,
        "aggregated_danger": 0,
        "thumbnail": {
          "slug": "bl6bjweeq6kty",
          "source": "https:\/\/robertsspaceindustries.com\/media\/bl6bjweeq6ktyr\/source\/Baker_System_Concept_Final-V2-Rotate.jpg",
          "images": {
            "post": "https:\/\/robertsspaceindustries.com\/media\/bl6bjweeq6ktyr\/post\/Baker_System_Concept_Final-V2-Rotate.jpg",
            "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/bl6bjweeq6ktyr\/product_thumb_large\/Baker_System_Concept_Final-V2-Rotate.jpg",
            "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/bl6bjweeq6ktyr\/subscribers_vault_thumbnail\/Baker_System_Concept_Final-V2-Rotate.jpg"
          }
        }
      }
    ]
  },
  "code": "OK",
  "msg": "OK"
}
