{
  "success": 1,
  "data": {
    "rowcount": 1,
    "totalrows": "1",
    "estimatedrows": false,
    "pagesize": 0,
    "pagecount": null,
    "page": 1,
    "offset": 0,
    "startrow": 0,
    "resultset": [
      {
        "id": "320",
        "status": "P",
        "time_modified": "2018-01-26 01:52:17",
        "type": "SINGLE_STAR",
        "name": "Nul",
        "code": "NUL",
        "position_x": "-18.14866400",
        "position_y": "-10.62140100",
        "position_z": "-2.23589850",
        "info_url": null,
        "habitable_zone_inner": "51.08000000",
        "habitable_zone_outer": "83.50000000",
        "frost_line": "266.00000000",
        "description": "A pulsating Cepheid star blasts Nul with heightened temperatures that make it difficult for Human habitation. This lead the UEE to leave the system unclaimed despite several attempts to terraform the worlds. Nul remained mostly uninhabited until 2571, when the UEES Olympus crashed into Ashana while attempting to eliminate anti-Messer activists. A small population of criminals, drifters and expatriates now call its wreckage home.\n",
        "shader_data": {
          "lightColor": "#fcffd2",
          "starfield": {
            "radius": 30,
            "count": 759.95660063228,
            "sizeMin": 1,
            "sizeMax": 1,
            "color1": "rgb(128,128,128)",
            "color2": "rgb(100,100,100)"
          },
          "planetsSize": {
            "min": 0.019519557775408,
            "max": 0.038039115550817,
            "kFactor": 0.86518136071983
          }
        },
        "affiliation": [
          {
            "id": "8",
            "name": "Unclaimed",
            "code": "UNC",
            "color": "#f6851f",
            "membership.id": "728"
          }
        ],
        "celestial_objects": [
          {
            "id": "1764",
            "time_modified": "2015-10-06 23:16:02",
            "type": "JUMPPOINT",
            "designation": "Nul - Croshaw",
            "name": null,
            "code": "NUL.JUMPPOINTS.CROSHAW",
            "age": "0.00000000",
            "distance": "3.00000000",
            "latitude": "-5.00000000",
            "longitude": "-146.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": null,
            "fairchanceact": "0",
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1766",
            "time_modified": "2015-10-09 02:06:29",
            "type": "JUMPPOINT",
            "designation": "Nul - Caliban",
            "name": null,
            "code": "NUL.JUMPPOINTS.CALIBAN",
            "age": "0.00000000",
            "distance": "4.10000000",
            "latitude": "12.00000000",
            "longitude": "-39.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": null,
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1768",
            "time_modified": "2015-10-09 02:06:05",
            "type": "JUMPPOINT",
            "designation": "Nul - Centauri",
            "name": null,
            "code": "NUL.JUMPPOINTS.CENTAURI",
            "age": "0.00000000",
            "distance": "3.30000000",
            "latitude": "-1.00000000",
            "longitude": "-49.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": null,
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1769",
            "time_modified": "2018-01-26 02:02:17",
            "type": "STAR",
            "designation": "Nul",
            "name": null,
            "code": "NUL.STARS.NUL",
            "age": "0.00000000",
            "distance": "0.00000000",
            "latitude": "0.00000000",
            "longitude": "0.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": null,
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": {
              "sun": {
                "color1": "#cda64d",
                "color2": "#fff778",
                "flare1": 0.265,
                "flare2": 0.5,
                "flare3": 0.265,
                "flare4": 0.29229100024319,
                "flare5": 0.80672316067119,
                "flare6": 0.1,
                "sphere": 1,
                "texture": 1,
                "corona": 1,
                "glow": 0.30398264025291,
                "alpha": 1,
                "rotation1": 0.6,
                "rotation2": 0.6,
                "map": 0,
                "iterations": 0,
                "scaleMin": 1.1107045023284,
                "scaleMax": 1,
                "scalePeriod": 1
              },
              "radius": 0.275,
              "orbitalMin": 1,
              "orbitalMax": 5,
              "orbitalFactor": 1
            },
            "size": "756258.16450000",
            "subtype_id": "4",
            "parent_id": null,
            "subtype": {
              "id": "4",
              "name": "Variable",
              "type": "STAR"
            },
            "affiliation": [],
            "population": []
          }, {
            "id": "1770",
            "time_modified": "2018-01-26 01:50:29",
            "type": "PLANET",
            "designation": "Nul I",
            "name": null,
            "code": "NUL.PLANETS.NULI",
            "age": "0.00000000",
            "distance": "1.30200000",
            "latitude": "0.00000000",
            "longitude": "60.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "95.00000000",
            "description": "An uninhabitable dwarf planet being burnt away by the system\u2019s pulsating star.   \n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "1",
            "sensor_economy": "1",
            "sensor_danger": "5",
            "shader_data": null,
            "size": "1020.00000000",
            "subtype_id": "21",
            "parent_id": "1769",
            "subtype": {
              "id": "21",
              "name": "Dwarf Planet",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "8",
                "name": "Unclaimed",
                "code": "UNC",
                "color": "#f6851f",
                "membership.id": "2961"
              }
            ],
            "population": [],
            "texture": {
              "slug": "jnd5qqer9z13g",
              "source": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/source\/Planet_Rocky.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/post\/Planet_Rocky.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/product_thumb_large\/Planet_Rocky.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/subscribers_vault_thumbnail\/Planet_Rocky.jpg"
              }
            }
          }, {
            "id": "1771",
            "time_modified": "2018-01-26 01:50:43",
            "type": "PLANET",
            "designation": "Nul II",
            "name": null,
            "code": "NUL.PLANETS.NULII",
            "age": "0.00000000",
            "distance": "2.10000000",
            "latitude": "0.00000000",
            "longitude": "-31.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "390.00000000",
            "description": "A large, iron planet too close to the star to be mined. Recently, the star\u2019s immense heat has cracked its surface, resulting in gas slowly leaking from its burnt mantle. \n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "1",
            "sensor_economy": "2",
            "sensor_danger": "6",
            "shader_data": null,
            "size": "6159.00000000",
            "subtype_id": "27",
            "parent_id": "1769",
            "subtype": {
              "id": "27",
              "name": "Iron Planet",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "8",
                "name": "Unclaimed",
                "code": "UNC",
                "color": "#f6851f",
                "membership.id": "2962"
              }
            ],
            "population": [],
            "texture": {
              "slug": "woi3qpzk18w05",
              "source": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/source\/Planet_Iron.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/post\/Planet_Iron.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/product_thumb_large\/Planet_Iron.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/woi3qpzk18w05r\/subscribers_vault_thumbnail\/Planet_Iron.jpg"
              }
            }
          }, {
            "id": "1772",
            "time_modified": "2018-01-26 01:51:10",
            "type": "PLANET",
            "designation": "Nul III",
            "name": "Cole",
            "code": "NUL.PLANETS.NULIIICOLE",
            "age": "0.00000000",
            "distance": "52.70000000",
            "latitude": "0.00000000",
            "longitude": "-115.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "500.00000000",
            "description": "Located on the edge of the habitable zone, Cole\u2019s atmosphere is composed of ammonia and sulfur. Char, an abandoned research station has a small population and is the only landing zone.\n",
            "info_url": null,
            "habitable": "1",
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "3",
            "sensor_economy": "4",
            "sensor_danger": "8",
            "shader_data": null,
            "size": "6641.00000000",
            "subtype_id": "55",
            "parent_id": "1769",
            "subtype": {
              "id": "55",
              "name": "Terrestrial Rocky",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "8",
                "name": "Unclaimed",
                "code": "UNC",
                "color": "#f6851f",
                "membership.id": "2963"
              }
            ],
            "population": [],
            "texture": {
              "slug": "jnd5qqer9z13g",
              "source": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/source\/Planet_Rocky.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/post\/Planet_Rocky.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/product_thumb_large\/Planet_Rocky.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/subscribers_vault_thumbnail\/Planet_Rocky.jpg"
              }
            }
          }, {
            "id": "1773",
            "time_modified": "2018-01-26 01:51:32",
            "type": "PLANET",
            "designation": "Nul IV",
            "name": null,
            "code": "NUL.PLANETS.NULIV",
            "age": "0.00000000",
            "distance": "73.29000000",
            "latitude": "0.00000000",
            "longitude": "146.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "1100.00000000",
            "description": "A gas giant suffering from a permanent electrical storm that makes refueling attempts deadly. \n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_GAS",
            "sensor_population": "1",
            "sensor_economy": "3",
            "sensor_danger": "7",
            "shader_data": null,
            "size": "57696.00000000",
            "subtype_id": "23",
            "parent_id": "1769",
            "subtype": {
              "id": "23",
              "name": "Gas Giant",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "8",
                "name": "Unclaimed",
                "code": "UNC",
                "color": "#f6851f",
                "membership.id": "2964"
              }
            ],
            "population": [],
            "texture": {
              "slug": "76ubmnk9zol8a",
              "source": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/source\/Planet_Gas.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/post\/Planet_Gas.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/product_thumb_large\/Planet_Gas.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/subscribers_vault_thumbnail\/Planet_Gas.jpg"
              }
            }
          }, {
            "id": "1774",
            "time_modified": "2018-01-26 01:51:46",
            "type": "PLANET",
            "designation": "Nul V",
            "name": "Ashana",
            "code": "NUL.PLANETS.NULVASHANA",
            "age": "0.00000000",
            "distance": "119.70000000",
            "latitude": "0.00000000",
            "longitude": "48.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "2410.00000000",
            "description": "A massive desert world known for its strong winds and shifting sand dunes. The only landing zone on the planet is the wreckage of the Olympus, now converted into an open black market for expatriates and criminals.\n",
            "info_url": null,
            "habitable": "1",
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "3",
            "sensor_economy": "4",
            "sensor_danger": "8",
            "shader_data": null,
            "size": "8700.00000000",
            "subtype_id": "56",
            "parent_id": "1769",
            "subtype": {
              "id": "56",
              "name": "Desert Planet",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "8",
                "name": "Unclaimed",
                "code": "UNC",
                "color": "#f6851f",
                "membership.id": "2965"
              }
            ],
            "population": [],
            "texture": {
              "slug": "spa7em2nu5nja",
              "source": "https:\/\/robertsspaceindustries.com\/media\/spa7em2nu5njar\/source\/Planet_Desert.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/spa7em2nu5njar\/post\/Planet_Desert.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/spa7em2nu5njar\/product_thumb_large\/Planet_Desert.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/spa7em2nu5njar\/subscribers_vault_thumbnail\/Planet_Desert.jpg"
              }
            }
          }, {
            "id": "1778",
            "time_modified": "2015-10-06 23:16:37",
            "type": "JUMPPOINT",
            "designation": "Nul - Vega",
            "name": null,
            "code": "NUL.JUMPPOINTS.VEGA",
            "age": "0.00000000",
            "distance": "4.60000000",
            "latitude": "-28.00000000",
            "longitude": "-103.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": null,
            "fairchanceact": "0",
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }
        ],
        "aggregated_size": "119.70000000",
        "aggregated_population": 8.32,
        "aggregated_economy": 1.63,
        "aggregated_danger": 0,
        "thumbnail": {
          "slug": "j4mxhdz651vkp",
          "source": "https:\/\/robertsspaceindustries.com\/media\/j4mxhdz651vkpr\/source\/PMS-Cover.jpg",
          "images": []
        }
      }
    ]
  },
  "code": "OK",
  "msg": "OK"
}
