{
  "success": 1,
  "data": {
    "rowcount": 1,
    "totalrows": "1",
    "estimatedrows": false,
    "pagesize": 0,
    "pagecount": null,
    "page": 1,
    "offset": 0,
    "startrow": 0,
    "resultset": [
      {
        "id": "329",
        "status": "P",
        "time_modified": "2018-01-25 03:25:38",
        "type": "SINGLE_STAR",
        "name": "Fora",
        "code": "FORA",
        "position_x": "2.65723510",
        "position_y": "-67.59278900",
        "position_z": "-50.63693200",
        "info_url": null,
        "habitable_zone_inner": "0.42000000",
        "habitable_zone_outer": "0.84000000",
        "frost_line": "2.16000000",
        "description": "Located near Banu territory, surveyors were hopeful that Fora system could become another major trade hub. Unfortunately, it\u2019s only habitable planet, Hyperion (Fora III), fell victim to a terraforming mishap that created a perpetual, planet-wide dust storm. Informal censuses of the area indicate that visitors are more likely to encounter a smuggler, outlaw or Banu settler than a UEE Citizen while in this five-planet system.\n",
        "shader_data": {
          "lightColor": "#f2c093",
          "starfield": {
            "radius": 25,
            "count": 759.95660063228,
            "sizeMin": 1,
            "sizeMax": 1,
            "color1": "rgb(128,128,128)",
            "color2": "rgb(100,100,100)"
          },
          "planetsSize": {
            "min": 0.010259778887704,
            "max": 0.079708120545485,
            "kFactor": 1
          }
        },
        "affiliation": [
          {
            "id": "1",
            "name": "UEE",
            "code": "uee",
            "color": "#48bbd4",
            "membership.id": "702"
          }
        ],
        "celestial_objects": [
          {
            "id": "1856",
            "time_modified": "2015-09-15 14:34:04",
            "type": "JUMPPOINT",
            "designation": "Fora - Rhetor",
            "name": null,
            "code": "FORA.JUMPPOINTS.RHETOR",
            "age": "0.00000000",
            "distance": "3.25000000",
            "latitude": "5.27900000",
            "longitude": "19.29750000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": "0",
            "fairchanceact": "0",
            "show_orbitlines": "0",
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1858",
            "time_modified": "2015-09-15 14:34:04",
            "type": "JUMPPOINT",
            "designation": "Fora - Nemo",
            "name": null,
            "code": "FORA.JUMPPOINTS.NEMO",
            "age": "0.00000000",
            "distance": "8.50000000",
            "latitude": "36.14690000",
            "longitude": "-121.62900000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": "0",
            "fairchanceact": "0",
            "show_orbitlines": "0",
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1859",
            "time_modified": "2015-09-15 14:34:04",
            "type": "JUMPPOINT",
            "designation": "Fora - Banshee",
            "name": null,
            "code": "FORA.JUMPPOINTS.BANSHEE",
            "age": "0.00000000",
            "distance": "14.00000000",
            "latitude": "16.21860000",
            "longitude": "-67.48150000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": "Jump Point",
            "info_url": null,
            "habitable": "0",
            "fairchanceact": "0",
            "show_orbitlines": "0",
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": null,
            "parent_id": null,
            "subtype": null,
            "affiliation": [],
            "population": []
          }, {
            "id": "1860",
            "time_modified": "2015-10-10 03:39:57",
            "type": "STAR",
            "designation": "Fora",
            "name": null,
            "code": "FORA.STARS.FORA",
            "age": "0.00000000",
            "distance": "0.00000000",
            "latitude": "0.00000000",
            "longitude": "0.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": null,
            "description": null,
            "info_url": null,
            "habitable": null,
            "fairchanceact": "0",
            "show_orbitlines": "0",
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "0",
            "sensor_economy": "0",
            "sensor_danger": "0",
            "shader_data": {
              "sun": {
                "color1": "#ed830b",
                "color2": "#d9d919",
                "flare1": 0.265,
                "flare2": 0.5,
                "flare3": 0.265,
                "flare4": 0.5,
                "flare5": 0.5,
                "flare6": 0.1,
                "sphere": 1,
                "texture": 1,
                "corona": 1,
                "glow": 0.5,
                "alpha": 1,
                "rotation1": 0.6,
                "rotation2": 0.6,
                "map": "4",
                "iterations": 0,
                "scaleMin": 1,
                "scaleMax": 1,
                "scalePeriod": 1
              },
              "radius": 0.03,
              "orbitalMin": 1,
              "orbitalMax": 5,
              "orbitalFactor": 1
            },
            "size": "618578.35450000",
            "subtype_id": "60",
            "parent_id": null,
            "subtype": {
              "id": "60",
              "name": "Main Sequence-Dwarf-K",
              "type": "STAR"
            },
            "affiliation": [],
            "population": []
          }, {
            "id": "1861",
            "time_modified": "2018-01-25 03:23:46",
            "type": "PLANET",
            "designation": "Fora I",
            "name": null,
            "code": "FORA.PLANETS.FORAI",
            "age": "0.00000000",
            "distance": "0.20890000",
            "latitude": "0.00000000",
            "longitude": "36.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "44.30000000",
            "description": "An uninhabited dwarf planet.\n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "1",
            "sensor_economy": "2",
            "sensor_danger": "2",
            "shader_data": null,
            "size": "2464.00000000",
            "subtype_id": "21",
            "parent_id": "1860",
            "subtype": {
              "id": "21",
              "name": "Dwarf Planet",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2847"
              }
            ],
            "population": [],
            "texture": {
              "slug": "jnd5qqer9z13g",
              "source": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/source\/Planet_Rocky.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/post\/Planet_Rocky.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/product_thumb_large\/Planet_Rocky.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/subscribers_vault_thumbnail\/Planet_Rocky.jpg"
              }
            }
          }, {
            "id": "1862",
            "time_modified": "2018-01-25 03:23:53",
            "type": "PLANET",
            "designation": "Fora II",
            "name": null,
            "code": "FORA.PLANETS.FORAII",
            "age": "0.00000000",
            "distance": "0.31300000",
            "latitude": "0.00000000",
            "longitude": "115.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "81.39000000",
            "description": "A coreless world that has few remaining resources after being thoroughly mined for the past several decades. \n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "1",
            "sensor_economy": "3",
            "sensor_danger": "3",
            "shader_data": null,
            "size": "6093.00000000",
            "subtype_id": "19",
            "parent_id": "1860",
            "subtype": {
              "id": "19",
              "name": "Coreless Planet",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2848"
              }
            ],
            "population": [],
            "texture": {
              "slug": "jnd5qqer9z13g",
              "source": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/source\/Planet_Rocky.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/post\/Planet_Rocky.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/product_thumb_large\/Planet_Rocky.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/subscribers_vault_thumbnail\/Planet_Rocky.jpg"
              }
            }
          }, {
            "id": "1863",
            "time_modified": "2018-01-25 03:24:05",
            "type": "PLANET",
            "designation": "Fora III",
            "name": "Hyperion",
            "code": "FORA.PLANETS.FORAIIIHYPERION",
            "age": "0.00000000",
            "distance": "0.47000000",
            "latitude": "0.00000000",
            "longitude": "-143.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "149.51000000",
            "description": "Swirling storms of red-hued HyperClay cover the surface of this world as a result of a problematic terraforming process, making life difficult for Hyperion\u2019s few residents.  \n",
            "info_url": null,
            "habitable": "1",
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BROWN",
            "sensor_population": "4",
            "sensor_economy": "5",
            "sensor_danger": "6",
            "shader_data": null,
            "size": "8560.00000000",
            "subtype_id": "55",
            "parent_id": "1860",
            "subtype": {
              "id": "55",
              "name": "Terrestrial Rocky",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2849"
              }
            ],
            "population": [],
            "texture": {
              "slug": "jnd5qqer9z13g",
              "source": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/source\/Planet_Rocky.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/post\/Planet_Rocky.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/product_thumb_large\/Planet_Rocky.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/jnd5qqer9z13gr\/subscribers_vault_thumbnail\/Planet_Rocky.jpg"
              }
            }
          }, {
            "id": "1864",
            "time_modified": "2018-01-25 03:26:45",
            "type": "ASTEROID_BELT",
            "designation": "Fora Belt Alpha",
            "name": null,
            "code": "FORA.BELTS.ALPHABELT",
            "age": "0.00000000",
            "distance": "0.52000000",
            "latitude": "0.00000000",
            "longitude": "0.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "172.49000000",
            "description": "A known drop point for smugglers to transfer contraband for others to transport them into Banu territory. This illegal activity can make it a dangerous place to travel through, especially with outlaws using the belt as a staging ground to ambush haulers entering or leaving the system.\n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": null,
            "show_label": "1",
            "appearance": "DEFAULT",
            "sensor_population": "1",
            "sensor_economy": "3",
            "sensor_danger": "6",
            "shader_data": null,
            "size": "0.00000000",
            "subtype_id": "50",
            "parent_id": "1860",
            "subtype": {
              "id": "50",
              "name": "System Belt",
              "type": "ASTEROID_BELT"
            },
            "affiliation": [],
            "population": []
          }, {
            "id": "1865",
            "time_modified": "2018-01-25 03:24:28",
            "type": "PLANET",
            "designation": "Fora V",
            "name": null,
            "code": "FORA.PLANETS.FORAV",
            "age": "0.00000000",
            "distance": "7.05000000",
            "latitude": "0.00000000",
            "longitude": "-52.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "8686.01000000",
            "description": "An ice giant with a water and ammonia atmosphere. \n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_BLUE",
            "sensor_population": "1",
            "sensor_economy": "1",
            "sensor_danger": "2",
            "shader_data": null,
            "size": "26179.00000000",
            "subtype_id": "25",
            "parent_id": "1860",
            "subtype": {
              "id": "25",
              "name": "Ice Giant",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2851"
              }
            ],
            "population": [],
            "texture": {
              "slug": "j52x7qoth74yi",
              "source": "https:\/\/robertsspaceindustries.com\/media\/j52x7qoth74yir\/source\/Planet_Ice.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/j52x7qoth74yir\/post\/Planet_Ice.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/j52x7qoth74yir\/product_thumb_large\/Planet_Ice.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/j52x7qoth74yir\/subscribers_vault_thumbnail\/Planet_Ice.jpg"
              }
            }
          }, {
            "id": "1866",
            "time_modified": "2018-01-25 03:24:21",
            "type": "PLANET",
            "designation": "Fora IV",
            "name": null,
            "code": "FORA.PLANETS.FORAIV",
            "age": "0.00000000",
            "distance": "2.35000000",
            "latitude": "0.00000000",
            "longitude": "-89.00000000",
            "axial_tilt": "0.00000000",
            "orbit_period": "1670.62000000",
            "description": "This gas giant is composed predominantly of hydrogen and helium.\n",
            "info_url": null,
            "habitable": null,
            "fairchanceact": null,
            "show_orbitlines": "1",
            "show_label": "1",
            "appearance": "PLANET_GAS",
            "sensor_population": "1",
            "sensor_economy": "2",
            "sensor_danger": "3",
            "shader_data": null,
            "size": "42304.00000000",
            "subtype_id": "23",
            "parent_id": "1860",
            "subtype": {
              "id": "23",
              "name": "Gas Giant",
              "type": "PLANET"
            },
            "affiliation": [
              {
                "id": "1",
                "name": "UEE",
                "code": "uee",
                "color": "#48bbd4",
                "membership.id": "2850"
              }
            ],
            "population": [],
            "texture": {
              "slug": "76ubmnk9zol8a",
              "source": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/source\/Planet_Gas.jpg",
              "images": {
                "post": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/post\/Planet_Gas.jpg",
                "product_thumb_large": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/product_thumb_large\/Planet_Gas.jpg",
                "subscribers_vault_thumbnail": "https:\/\/robertsspaceindustries.com\/media\/76ubmnk9zol8ar\/subscribers_vault_thumbnail\/Planet_Gas.jpg"
              }
            }
          }
        ],
        "aggregated_size": "14.00000000",
        "aggregated_population": 8.33,
        "aggregated_economy": 1.86,
        "aggregated_danger": 0
      }
    ]
  },
  "code": "OK",
  "msg": "OK"
}
