module.exports = {
  AGES_RANGES: [
    'young',
    'mature',
    'ancient'
  ],
  CLASSIFICATIONS_SHAPES: [
    'elliptical',
    'spiral-2',
    'spiral-3',
    'spiral-4',
    'cluster',
    'disc',
    'box',
    'irregular',
    'ring',
  ],
  CONSTELATIONS_NAMES: [
    'centauri',
    'andromeda',
    'antlia',
    'aquarius',
    'aquila',
    'ara',
    'aries',
    'auriga',
    'bootes',
    'caelum',
    'camelopardalis',
    'cancer',
    'canes venatici',
    'canis major',
    'canis minor',
    'capricornus',
    'carina',
    'cassiopeia',
    'centaurus',
    'cepheus',
    'cetus',
    'chamaeleon',
    'circinus',
    'columba',
    'coma berenices',
    'corona australis',
    'corona borealis',
    'corvus',
    'crater',
    'crux',
    'cygnus',
    'dephinus',
    'dorado',
    'draco',
    'equuleus',
    'eridanus',
    'fornax',
    'gemini',
    'grus',
    'hercules',
    'horologium',
    'hydra',
    'hydrus',
    'indus',
    'lacerta',
    'leo',
    'leo minor',
    'lepus',
    'libra',
    'lupus',
    'lynx',
    'lyra',
    'mensa',
    'microscopium',
    'monoceros',
    'musca',
    'norma',
    'octans',
    'ophiuchus',
    'orion',
    'pavo',
    'pegasus',
    'perseus',
    'phoenix',
    'pictor',
    'pisces',
    'piscis austrinus',
    'puppis',
    'pyxis',
    'reticulum',
    'sagitta',
    'sagittarius',
    'scorpius',
    'sculptor',
    'scutum',
    'serpens',
    'sextans',
    'taurus',
    'telescopium',
    'triangulum',
    'triangulum australe',
    'tucana',
    'ursa major',
    'ursa minor',
    'vela',
    'virgo',
    'volans',
    'vulpecula',
    // OLD
    'anguilla',
    'antinous',
    'apes',
    'apis',
    'aranea',
    'argo navis',
    'asselli',
    'praesepe',
    'asterion',
    'chara',
    'battery',
    'volta',
    'bufo',
    'cancer minor',
    'capra',
    'haedi',
    'cerberus',
    'corona firmiana',
    // https://en.wikipedia.org/wiki/Former_constellations
  ]
}
